# Generated by Django 5.2.1 on 2025-05-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_answer_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
    ]
