# Generated by Django 5.2.1 on 2025-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
