# Generated by Django 5.2.1 on 2025-05-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_product",
            old_name="price",
            new_name="total_price",
        ),
    ]
